[build-system]
requires = ['setuptools>=61.0']
build-backend = 'setuptools.build_meta'

[project]
name = 'registrar'
version = '1.0.1'
description = ''
authors = [
    { name = 'Садовский М.К.', email = 'i@maxim-sadovskiy.ru' }
]
license = { text = 'Apache-2.0' }
readme = 'README.md'
requires-python = '>=3.8'

[project.optional-dependencies]
my_id = [
    "my_id @ git+https://github.com/Sam-Strand/my_id.git",
]

[project.urls]
Homepage = 'https://github.com/Sam-Strand/registrar_py'
